# Generated by Django 3.1.4 on 2021-01-25 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulica', models.CharField(max_length=45)),
                ('kod', models.CharField(max_length=6)),
                ('miasto', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ('miasto',),
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=60)),
                ('cena', models.DecimalField(decimal_places=2, default=5000, max_digits=15)),
                ('typ', models.CharField(max_length=60)),
                ('producent', models.CharField(max_length=60)),
                ('gwarancja', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('nazwa',),
            },
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.DecimalField(decimal_places=2, default=5000, max_digits=15)),
                ('numer_zamowienia', models.CharField(max_length=20)),
                ('zprodukt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zadres', to='zamowienia.adres')),
            ],
            options={
                'ordering': ('numer_zamowienia',),
            },
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=60)),
                ('nazwisko', models.CharField(max_length=60)),
                ('telefon', models.CharField(max_length=20)),
                ('pesel', models.CharField(max_length=20)),
                ('zarobki', models.DecimalField(decimal_places=2, default=5000, max_digits=9)),
                ('padres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padres', to='zamowienia.adres')),
                ('pzamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pzamowienie', to='zamowienia.zamowienie')),
            ],
            options={
                'ordering': ('imie',),
            },
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=60)),
                ('nazwisko', models.CharField(max_length=60)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('kadres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kadres', to='zamowienia.adres')),
                ('kzamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kzamowienie', to='zamowienia.zamowienie')),
            ],
            options={
                'ordering': ('imie',),
            },
        ),
    ]
