# Generated by Django 3.1.5 on 2021-01-28 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ('nazwa',),
            },
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=40)),
                ('nazwisko', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ('nazwisko',),
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
                ('producent', models.CharField(max_length=40)),
                ('opis', models.CharField(max_length=200)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro', to='sklep_API.kategoria')),
            ],
            options={
                'ordering': ('nazwa',),
            },
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zam', to='sklep_API.klient')),
                ('id_produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro', to='sklep_API.produkt')),
            ],
            options={
                'ordering': ('kwota',),
            },
        ),
    ]
