# Generated by Django 3.1.5 on 2021-02-01 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklep_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='opis',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='id_klient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamowienia', to='sklep_API.klient'),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='kwota',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
